/**
 * Slovenia site configuration.
 * This is the only file that differs between installations.
 * Fork this file (and the public/ assets) to create a new country site.
 */

const siteConfig = {
  // Branding
  logo:        '/srd-logo-transparent.png',
  logoAlt:     'Slovensko rodoslovno društvo',
  societyUrl:  'https://rodoslovje.si',
  indexUrl:    'https://rodoslovje.si/rodoslovni-indeks/',
  contactEmail: 'indeks@rodoslovje.si',

  apiHost: 'indeks-api.rodoslovje.si',
  authUrl: 'https://rodoslovje.si/wp-json/jwt-auth/v1/token',
  filePrefix: 'sgi',

  // Languages shown in the dropdown, ordered alphabetically by language name
  languages: ['de', 'en', 'hr', 'hu', 'it', 'sl'],

  // Preferred language when no saved preference or browser match is found
  defaultLang: 'sl',

  // Per-language overrides: site title and society name
  i18n: {
    en: { site_title: 'Slovenian Genealogical Index',      society_name: 'Slovenian Genealogy Society' },
    sl: { site_title: 'Slovenski rodoslovni indeks',       society_name: 'Slovensko rodoslovno društvo' },
    hr: { site_title: 'Slovenski rodoslovni indeks',       society_name: 'Slovensko rodoslovno društvo' },
    hu: { site_title: 'Szlovén Genealógiai Index',         society_name: 'Szlovén Genealógiai Társaság' },
    de: { site_title: 'Slowenischer Genealogischer Index', society_name: 'Slowenische Genealogische Gesellschaft' },
    it: { site_title: 'Indice genealogico sloveno',        society_name: 'Società genealogica slovena' },
  },

  // Intro paragraphs shown on empty search tabs. Falls back to 'en' for missing languages.
  // Each entry: { text: string (HTML allowed), warning?: true }
  intro: {
    en: [
      { text: '<strong>The Slovenian Genealogical Index</strong> is an archival collection of data on persons and families in Slovenia, built from the collections of individual genealogists since the very beginning of the society\'s activities. In it you can search for the names and surnames of the people you are researching, to find out whether someone else may have already discovered and described them. The basic index contains personal names, dates and places of birth, marriage and death, as well as links to parents, partners and children. Each record also includes the surname of the contributing genealogist, which lets the researcher make further contact, points the way, and often makes research possible in a parish discovered indirectly. The contact details of the genealogists are not published, but they will not be difficult to reach through the <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slovenian Genealogy Society</a>.' },
      { text: 'The application offers advanced search, sorting, and data export options. For detailed instructions on using all features, please see the <a href="#" onclick="document.getElementById(\'help-toggle-btn\')?.click(); return false;">user manual</a>.' },
      { text: 'The family index can also include parents who never married or even never lived together &ndash; valuable information for descendants and other researchers.' },
      { text: 'The index is built from data in GEDCOM files contributed by many genealogists, listed on the <a href="?t=contributors">Genealogists</a> page.' },
      { text: 'You can also contribute indexed <a href="https://data.matricula-online.eu" target="_blank" rel="noopener">Matricula</a> parish registers (baptisms, marriages, deaths) in CSV or XLS format. Several genealogists have already contributed indexes for entire books in individual parishes. The list is available on the <a href="?t=matricula">Matricula index</a> page.' },
      { text: 'Warning! The Slovenian Genealogical Index is for informational purposes only. The Slovenian Genealogy Society disclaims all responsibility for the accuracy of the data submitted. The society is a voluntary association of individuals who together develop a shared knowledge source drawn from parish registers and other written and oral sources. Its structure allows anyone with their own collection of genealogical data to contribute it to the shared cumulative collection and index. Neither the individual contributors nor the Slovenian Genealogy Society can guarantee the accuracy of the data.', warning: true },
      { text: 'If you keep your own family tree in a database and would like to join the existing contributors with the results of your work, export the data to a GEDCOM file (without data on living persons) and send it to the administrator by <a href="mailto:indeks@rodoslovje.si">email</a>.' },
    ],
    sl: [
      { text: '<strong>Slovenski rodoslovni indeks</strong> je arhivska zbirka podatkov o osebah in družinah na Slovenskem, ki nastaja iz zbirk posameznih rodoslovcev že od samega začetka delovanja društva. V njej lahko poiščete imena in priimke oseb, ki jih raziskujete, da bi ugotovili, ali jih je morda odkril in popisal že kdo drug. Osnovni indeks vsebuje osebna imena, datume in kraje rojstev, porok in smrti, prav tako pa tudi povezave do staršev, partnerjev in otrok. Pri vsakem zapisu je tudi priimek rodoslovca &ndash; dajalca podatkov, kar iskalcu omogoči nadaljnji stik, nakaže smer in pogosto sploh omogoči nadaljnje raziskovanje v posredno odkriti župniji. Kontaktni podatki rodoslovcev sicer niso objavljeni, vendar do njih ne bo težko priti prek <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slovenskega rodoslovnega društva</a>.' },
      { text: 'Aplikacija ponuja napredne možnosti iskanja, razvrščanja in izvoza podatkov. Za podrobnejša navodila o uporabi vseh funkcionalnosti si oglejte <a href="#" onclick="document.getElementById(\'help-toggle-btn\')?.click(); return false;">navodila za uporabo</a>.' },
      { text: 'Indeks družin lahko vsebuje tudi starše, ki nikoli niso bili poročeni ali celo nikoli niso živeli skupaj, kar je lahko dragocen podatek za potomce oziroma iskalce informacij.' },
      { text: 'Indeks je sestavljen iz podatkov v datotekah GEDCOM, ki so nam jih posredovali številni rodoslovci, navedeni na strani <a href="?t=contributors">Rodoslovci</a>.' },
      { text: 'V indeks je možno prispevati tudi indeksirane <a href="https://data.matricula-online.eu" target="_blank" rel="noopener">Matricula</a> matične knjige (krstne, poročne, mrliške) v obliki CSV ali XLS. Do sedaj je že kar nekaj rodoslovcev prispevalo indekse za celotne knjige v posameznih župnijah. Seznam je na voljo na strani <a href="?t=matricula">Matricula indeks</a>.' },
      { text: 'Opozorilo! Slovenski rodoslovni indeks je informativnega značaja. Slovensko rodoslovno društvo se odreka vsakršni odgovornosti za pravilnost posredovanih podatkov. Društvo je prostovoljna povezava posameznikov, ki razvijajo skupni vir znanja o podatkih iz matičnih registrov ter drugih pisnih in ustnih virov. Struktura društva omogoča, da lahko vsak, ki ima svojo zbirko rodoslovnih podatkov, to prispeva v skupno kumulativno zbirko in indeks. Za pravilnost podatkov ne jamči niti posameznik, ki jih je prispeval, niti Slovensko rodoslovno društvo.', warning: true },
      { text: 'Če imate svoj rodovnik v obliki zbirke podatkov in bi se dosedanjim sodelavcem želeli pridružiti z rezultati svojega dela, izvozite podatke v datoteko GEDCOM (brez podatkov o še živih osebah) in jo po <a href="mailto:indeks@rodoslovje.si">e-pošti</a> pošljite administratorju.' },
    ],
    hr: [
      { text: '<strong>Slovenski rodoslovni indeks</strong> arhivska je zbirka podataka o osobama i obiteljima u Sloveniji, koja nastaje iz zbirki pojedinih rodoslovaca od samih početaka rada društva. U njoj možete tražiti imena i prezimena osoba koje istražujete kako biste saznali je li ih netko drugi već otkrio i opisao. Osnovni indeks sadrži osobna imena, datume i mjesta rođenja, vjenčanja i smrti te poveznice na roditelje, partnere i djecu. Uz svaki zapis stoji i prezime rodoslovca &ndash; davatelja podataka, što istraživaču omogućuje daljnji kontakt, naznačuje smjer i često uopće omogućuje daljnje istraživanje u posredno otkrivenoj župi. Kontaktni podaci rodoslovaca nisu objavljeni, no do njih neće biti teško doći putem <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slovenskog rodoslovnog društva</a>.' },
      { text: 'Aplikacija nudi napredne mogućnosti pretraživanja, sortiranja i izvoza podataka. Za detaljnije upute o korištenju svih funkcionalnosti pogledajte <a href="#" onclick="document.getElementById(\'help-toggle-btn\')?.click(); return false;">upute za korištenje</a>.' },
      { text: 'Indeks obitelji može uključivati i roditelje koji se nikada nisu vjenčali ili čak nikada nisu živjeli zajedno, što može biti dragocjena informacija za potomke ili druge istraživače.' },
      { text: 'Indeks je sastavljen od podataka iz datoteka GEDCOM koje su nam ustupili brojni rodoslovci, navedeni na stranici <a href="?t=contributors">Rodoslovci</a>.' },
      { text: 'U indeks je moguće priložiti i indeksirane matične knjige <a href="https://data.matricula-online.eu" target="_blank" rel="noopener">Matricula</a> (krštenih, vjenčanih, umrlih) u CSV ili XLS obliku. Dosad je već nekoliko rodoslovaca priložilo indekse za cijele knjige u pojedinim župama. Popis je dostupan na stranici <a href="?t=matricula">Matricula indeks</a>.' },
      { text: 'Upozorenje! Slovenski rodoslovni indeks isključivo je informativnog karaktera. Slovensko rodoslovno društvo odriče se svake odgovornosti za točnost dostavljenih podataka. Društvo je dobrovoljno udruženje pojedinaca koji zajedno razvijaju zajednički izvor znanja o podacima iz matičnih knjiga te drugih pisanih i usmenih izvora. Struktura društva omogućuje svakome tko ima vlastitu zbirku rodoslovnih podataka da je doprinese zajedničkoj kumulativnoj zbirci i indeksu. Za točnost podataka ne jamči ni pojedinac koji ih je dao ni Slovensko rodoslovno društvo.', warning: true },
      { text: 'Ako imate vlastito obiteljsko stablo u obliku baze podataka i željeli biste se pridružiti dosadašnjim suradnicima rezultatima svojega rada, izvezite podatke u datoteku GEDCOM (bez podataka o živim osobama) i pošaljite je administratoru <a href="mailto:indeks@rodoslovje.si">e-poštom</a>.' },
    ],
    hu: [
      { text: '<strong>A Szlovén Genealógiai Index</strong> szlovéniai személyek és családok adatainak archív gyűjteménye, amely a társaság megalakulása óta az egyes genealógusok gyűjteményeiből épül fel. Itt rákereshet azoknak a személyeknek a nevére és vezetéknevére, akiket kutat, hogy megtudja, valaki más már felfedezte és leírta-e őket. Az alapindex személyneveket, születési, házassági és halálozási dátumokat és helyszíneket tartalmaz, valamint a szülőkre, partnerekre és gyermekekre mutató hivatkozásokat. Minden bejegyzéshez tartozik az adatszolgáltató genealógus vezetékneve is, ami lehetővé teszi a további kapcsolatfelvételt, irányt mutat, és sokszor egyáltalán lehetővé teszi a közvetve felfedezett plébánián való kutatást. A genealógusok elérhetőségei nincsenek közzétéve, de a <a href="https://rodoslovje.si" target="_blank" rel="noopener">Szlovén Genealógiai Társaságon</a> keresztül nem lesz nehéz eljutni hozzájuk.' },
      { text: 'Az alkalmazás fejlett keresési, rendezési és adatexportálási lehetőségeket kínál. Az összes funkció használatára vonatkozó részletes utasításokért tekintse meg a <a href="#" onclick="document.getElementById(\'help-toggle-btn\')?.click(); return false;">használati útmutatót</a>.' },
      { text: 'A családindex olyan szülőket is tartalmazhat, akik soha nem házasodtak össze, vagy akár soha nem is éltek együtt &ndash; ez értékes információ lehet a leszármazottak vagy más kutatók számára.' },
      { text: 'Az index a GEDCOM-fájlokban található adatokból áll össze, amelyeket számos genealógus küldött el nekünk; ők a <a href="?t=contributors">Genealógusok</a> oldalon vannak felsorolva.' },
      { text: 'Az indexbe indexelt <a href="https://data.matricula-online.eu" target="_blank" rel="noopener">Matricula</a>-anyakönyveket (kereszteltek, házasultak, halottak) is be lehet küldeni CSV vagy XLS formátumban. Eddig már több genealógus is hozzájárult egész könyvek indexeivel az egyes plébániákon. A lista a <a href="?t=matricula">Matricula index</a> oldalon érhető el.' },
      { text: 'Figyelmeztetés! A Szlovén Genealógiai Index kizárólag tájékoztató jellegű. A Szlovén Genealógiai Társaság minden felelősséget elhárít a benyújtott adatok pontosságáért. A társaság olyan egyének önkéntes egyesülete, akik közösen fejlesztik az anyakönyvekből és más írott és szóbeli forrásokból származó adatok közös tudásforrását. A társaság felépítése lehetővé teszi, hogy mindenki, akinek saját genealógiai adatgyűjteménye van, hozzájáruljon vele a közös kumulatív gyűjteményhez és indexhez. Az adatok pontosságáért sem az adatokat hozzájáruló egyén, sem a Szlovén Genealógiai Társaság nem vállal felelősséget.', warning: true },
      { text: 'Ha saját családfáját adatbázis formájában tárolja, és szeretne a meglévő közreműködőkhöz csatlakozni munkája eredményével, exportálja az adatokat GEDCOM-fájlba (élő személyek adatai nélkül), és küldje el a rendszergazdának <a href="mailto:indeks@rodoslovje.si">e-mailben</a>.' },
    ],
    de: [
      { text: '<strong>Der Slowenische Genealogische Index</strong> ist eine Archivsammlung von Daten über Personen und Familien in Slowenien, die seit den Anfängen der Gesellschaft aus den Sammlungen einzelner Genealogen entsteht. Darin können Sie nach Namen und Nachnamen der Personen suchen, die Sie erforschen, um herauszufinden, ob sie bereits jemand anderes entdeckt und beschrieben hat. Der Grundindex enthält Personennamen, Daten und Orte von Geburten, Heiraten und Sterbefällen sowie Verweise auf Eltern, Partner und Kinder. Zu jedem Eintrag gehört auch der Nachname des datenliefernden Genealogen, was dem Forscher die weitere Kontaktaufnahme erlaubt, die Richtung weist und oft überhaupt erst die Recherche in einer indirekt entdeckten Pfarrei ermöglicht. Die Kontaktdaten der Genealogen sind nicht veröffentlicht, doch dürfte es nicht schwerfallen, sie über die <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slowenische Genealogische Gesellschaft</a> zu erreichen.' },
      { text: 'Die Anwendung bietet erweiterte Such-, Sortier- und Datenexportoptionen. Für detaillierte Anweisungen zur Nutzung aller Funktionen lesen Sie bitte das <a href="#" onclick="document.getElementById(\'help-toggle-btn\')?.click(); return false;">Benutzerhandbuch</a>.' },
      { text: 'Der Familienindex kann auch Eltern enthalten, die nie geheiratet oder sogar nie zusammengelebt haben &ndash; eine wertvolle Information für Nachkommen und andere Forschende.' },
      { text: 'Der Index entsteht aus Daten in GEDCOM-Dateien, die uns zahlreiche Genealogen zur Verfügung gestellt haben; sie sind auf der Seite <a href="?t=contributors">Genealogen</a> aufgeführt.' },
      { text: 'Zum Index können auch indexierte <a href="https://data.matricula-online.eu" target="_blank" rel="noopener">Matricula</a>-Pfarrmatrikeln (Tauf-, Trau-, Sterbebücher) im CSV- oder XLS-Format beigetragen werden. Bisher haben bereits mehrere Genealogen Indexe für ganze Bücher in einzelnen Pfarreien beigesteuert. Die Liste ist auf der Seite <a href="?t=matricula">Matricula-Index</a> verfügbar.' },
      { text: 'Warnung! Der Slowenische Genealogische Index dient ausschließlich Informationszwecken. Die Slowenische Genealogische Gesellschaft lehnt jegliche Verantwortung für die Richtigkeit der übermittelten Daten ab. Die Gesellschaft ist ein freiwilliger Zusammenschluss von Einzelpersonen, die gemeinsam eine Wissensquelle aus Pfarrmatrikeln sowie weiteren schriftlichen und mündlichen Quellen entwickeln. Ihre Struktur erlaubt es jedem, der eine eigene Sammlung genealogischer Daten besitzt, diese zur gemeinsamen kumulativen Sammlung und zum Index beizutragen. Für die Richtigkeit der Daten haftet weder die Einzelperson, die sie beigesteuert hat, noch die Slowenische Genealogische Gesellschaft.', warning: true },
      { text: 'Wenn Sie Ihren eigenen Stammbaum als Datenbank pflegen und sich den bisherigen Mitwirkenden mit den Ergebnissen Ihrer Arbeit anschließen möchten, exportieren Sie die Daten in eine GEDCOM-Datei (ohne Daten zu noch lebenden Personen) und senden Sie sie per <a href="mailto:indeks@rodoslovje.si">E-Mail</a> an den Administrator.' },
    ],
    it: [
      { text: '<strong>L\'Indice genealogico sloveno</strong> è una raccolta archivistica di dati su persone e famiglie in Slovenia, costituita a partire dalle collezioni dei singoli genealogisti fin dagli inizi dell\'attività della società. Vi può cercare i nomi e i cognomi delle persone che sta ricercando, per scoprire se qualcun altro le abbia già individuate e descritte. L\'indice di base contiene nomi, date e luoghi di nascita, matrimonio e morte, nonché i collegamenti a genitori, partner e figli. A ogni voce è associato anche il cognome del genealogista &ndash; fornitore dei dati, il che permette al ricercatore di stabilire un ulteriore contatto, ne indica la direzione e spesso rende possibile la ricerca in una parrocchia individuata in modo indiretto. I dati di contatto dei genealogisti non sono pubblicati, ma non sarà difficile raggiungerli tramite la <a href="https://rodoslovje.si" target="_blank" rel="noopener">Società genealogica slovena</a>.' },
      { text: 'L\'applicazione offre opzioni avanzate di ricerca, ordinamento ed esportazione dei dati. Per istruzioni dettagliate sull\'utilizzo di tutte le funzionalità, consultare il <a href="#" onclick="document.getElementById(\'help-toggle-btn\')?.click(); return false;">manuale d\'uso</a>.' },
      { text: 'L\'indice delle famiglie può comprendere anche genitori che non si sono mai sposati o che addirittura non hanno mai vissuto insieme &ndash; un\'informazione che può rivelarsi preziosa per i discendenti o per altri ricercatori.' },
      { text: 'L\'indice è composto da dati provenienti da file GEDCOM che ci sono stati forniti da numerosi genealogisti, elencati nella pagina <a href="?t=contributors">Genealogisti</a>.' },
      { text: 'All\'indice è possibile contribuire anche con registri parrocchiali <a href="https://data.matricula-online.eu" target="_blank" rel="noopener">Matricula</a> indicizzati (battesimi, matrimoni, decessi) in formato CSV o XLS. Finora diversi genealogisti hanno già contribuito con indici di interi libri in singole parrocchie. L\'elenco è disponibile nella pagina <a href="?t=matricula">Indice Matricula</a>.' },
      { text: 'Avvertenza! L\'Indice genealogico sloveno ha carattere puramente informativo. La Società genealogica slovena declina ogni responsabilità per l\'esattezza dei dati forniti. La società è un\'associazione volontaria di persone che sviluppano insieme una fonte comune di conoscenza, attinta da registri parrocchiali e da altre fonti scritte e orali. La sua struttura consente a chiunque possieda una propria raccolta di dati genealogici di contribuirla alla raccolta cumulativa comune e all\'indice. Per l\'esattezza dei dati non rispondono né la singola persona che li ha forniti né la Società genealogica slovena.', warning: true },
      { text: 'Se conserva il proprio albero genealogico in forma di database e desidera unirsi ai contributori già esistenti con i risultati del suo lavoro, esporti i dati in un file GEDCOM (esclusi i dati sulle persone viventi) e lo invii all\'amministratore tramite <a href="mailto:indeks@rodoslovje.si">e-mail</a>.' },
    ],
  },
};

export default siteConfig;
